export const SampleMsgList = [
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 1, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 1, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 1, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 1, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 1, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 1, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
  { id: 1, message_text: "Hello", user_id: 2, created_at: "10.20 PM" },
];
