name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - develop  # Trigger on push to the develop branch

jobs:
  deploy:
    name: Deploy to AWS Lightsail
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js (Optional, if your app is Node.js-based)
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Change as per your version

    - name: Install Dependencies
      run: |
        npm install 
        npm run build 

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
        
    - name: Start or Restart the App with PM2
      run: |
        ssh -o StrictHostKeyChecking=no bitnami@13.127.103.18 "
          cd /opt/bitnami/SocietyManagementFrontendV2 && 
          git pull origin develop && 
          npm install &&
          if pm2 describe app_name > /dev/null; then 
            pm2 restart app_name; 
          else 
            pm2 start npm --name app_name -- run start; 
          fi
        "

    - name: Notify Success
      run: echo "Deployment to AWS Lightsail successful!"